source/publishing_data/07_configuring_visualizations/06_configuring_custom_view/custom.rst

https://app.clubhouse.io/opendatasoft/story/14232/the-link-to-font-awesome-in-the-dataset-custom-tab-documentation-points-to-v5-should-be-4-7

[ch14232] Fix fontawesome links to icons list.

---

source/_themes/ods-theme/header.html

I added in the header links, a variable that contains the current language, this allows to continue navigation to other documentation with the chosen language.
**Multilingual documentation :**
Help Hub
Platform documentation
FAQ documentation

[ch14451] added current langage in header links

---

source/configuring_domain/01_managing_security/saml.rst
source/publishing_data/05_processing_data/processors/join_dataset.rst

This documents the fact that the join dataset now outputs the file identifier instead of name when gathering a file type field, and adds documentation for the user profile URL, EntityID customization and login link text customization in SAML documentation.

Join Dataset and SAML minor doc update

---

source/publishing_data/01_creating_a_dataset/supported_formats.rst

Any other encoding may result in modified file names (like removed accents), or even errors.

Recommend UTF-8 for file name encoding in zip files

---

source/managing_domain/01_managing_users_and_groups/users.rst

The "Look & Feel > Dataset Themes" was mentioned as been available with this permission only but it requires Edit Domain

Fix "Manage the domain theme" permission list

---

source/_templates/header.html

This PR adds a link to the [release notes](https://documentation-resources.opendatasoft.com/pages/release-notes/?headless=true) in the navigation header, so that users can access this page when browsing the user guide.
Story details: https://app.clubhouse.io/opendatasoft/story/26719
- Added a new link to the release notes in the navigation header.
- Created a "key", so that the "Release notes" link text gets translated.

Link to release notes in navigation header

---

source/_templates/layout.html

This PR removes GA and HubSpot scripts from the layout template for the user guide.
Story details: https://app.clubhouse.io/opendatasoft/story/26921
- Removed GA and HubSpot scripts from the [HTML layout template](https://github.com/opendatasoft/ods-documentation/compare/feature/ch26921/remove-ga-and-hubspot-tracking?expand=1#diff-a6bb33d393926ce378affaa784b1e6989b336361be73b9aeb9153cb594b36371)

[Cookies compliance] Removed GA & HubSpot scripts from layout template

---

source/exploring_catalog_and_datasets/03_searching_the_data/search.rst

This pull request adds the `#startswith` query to the data filtering methods.
Story details: https://app.clubhouse.io/opendatasoft/story/26613
- Added the [`#startswith`](https://github.com/opendatasoft/ods-documentation/compare/feature/ch26613/filter-data-using-startswith?expand=1#diff-246a20ddaac22d01953efe6e61084e7869695c5db4d49130a7913f7663d5f1d8R45-R52) method in the "Searching in the data section" of the user guide with a description and an example.

Added #startswith to data filtering methods

---

source/publishing_data/04_configuring_a_source/connectors/osm.rst

This pull request improves the documentation for the [OSM connector](https://help.opendatasoft.com/platform/en/publishing_data/04_configuring_a_source/connectors/osm.html#osm-connector).
Story details: https://app.clubhouse.io/opendatasoft/story/26457
- Added the missing [Load additional OSM versioning metadata](https://github.com/opendatasoft/ods-documentation/compare/chore/ch26457/improve-osm-connector-docs?expand=1#diff-7f37ac390bba2832814f305c1445938a68e170aa7450d9ad4434c22a4e1d9a33R30-R32) and [Use centroid for polygons instead of shapes](https://github.com/opendatasoft/ods-documentation/compare/chore/ch26457/improve-osm-connector-docs?expand=1#diff-7f37ac390bba2832814f305c1445938a68e170aa7450d9ad4434c22a4e1d9a33R30-R32) configuration options to the documentation.
- Fixed the …

Improve OSM connector documentation

---

source/exploring_catalog_and_datasets/03_searching_the_data/search.rst

This pull request adds `keyword` to the list of available fields in ODSQL [field queries](https://help.opendatasoft.com/platform/en/exploring_catalog_and_datasets/03_searching_the_data/search.html#field-queries).
Story details: https://app.clubhouse.io/opendatasoft/story/27113
- Added the [`keyword`](https://github.com/opendatasoft/ods-documentation/compare/bug/ch27113/add-keyword-to-odsql-field-queries?expand=1#diff-246a20ddaac22d01953efe6e61084e7869695c5db4d49130a7913f7663d5f1d8R140-R141) field to the list of available fields with a description.

Added keyword to ODSQL field queries

---

source/configuring_domain/03_managing_tracking/third_party_analytics.rst

- Mention that the tracking is restricted to the front-office (and move the mention to the top, instead of replicating it once per tracking provider)
- Mention that only Universal Analytics properties are supported by the Google Analytics integration

Update third-party analytics doc

---

source/publishing_data/02_harvesting_a_catalog/harvesters/ftp_with_meta_csv.rst
source/publishing_data/05_processing_data/processors/retrieve_administrative_divisions.rst

This PR aims to update the metadata accepted as columns in the documentation for the FTP Harvester with CSV metadata
Story details: https://app.clubhouse.io/opendatasoft/story/25583
- Replaced geographic_area* with geographic_reference* metadata
- Added info about geographic_reference* metadata
- Added info about the syntaxes for georeference UIDs
- Fixed a typo in the Metadata CSV file section

Update FTP harvester documentation concerning geonav metadata

---

source/customizing_look_and_feel/01_branding_portal/branding.rst
source/customizing_look_and_feel/03_adding_assets/assets.rst
source/publishing_data/01_creating_a_dataset/sourcing_data.rst
source/publishing_data/06_configuring_metadata/configuring_metadata.rst
source/publishing_data/08_configuring_dataset_export/configuring_dataset_export.rst

This pull request adds information related to the fact that metadata are not stripped from files uploaded to the platform.
Story details: https://app.clubhouse.io/opendatasoft/story/25558
- Added notes [here](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25558/metadata-not-stripped-in-uploaded-files?expand=1#diff-ca35bb0013f9a02d3aa2913d7309b67c3b3ef24a404edec3e8d89fb9bf3486d5R10-R13) and [there](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25558/metadata-not-stripped-in-uploaded-files?expand=1#diff-446ec72b2ee7642b57cda1cc394af7875ce9656ee479203344ea8c514c1d52abR30-R33) about metadata handling in uploaded files with a recommendation about stripping metadata from files before uploading them.
- Slightly reworked the …

Added notes about metadata stripping in uploaded files

---

source/_templates/footer.html

This pull removed Disqus from the User Guide. Due to ads being displayed before, after, and between comments, this commenting system cannot be used in the docs anymore.
Story details: https://app.clubhouse.io/opendatasoft/story/27712
- Removed Disqus `div` and `script` from the footer HTML template.

Removed Disqus from footer template

---

source/publishing_data/05_processing_data/processors/expression.rst

This pull request adds examples in the expression processor documentation. These examples show usage of the `now()` function nested in date functions.
Story details: https://app.clubhouse.io/opendatasoft/story/26459
- Added examples.

Expression processor: Added examples of expressions using now() in date functions

---

source/publishing_data/05_processing_data/processors/geocode_with_arcgis.rst

This pull request adds more information in the docs about the prerequisites to use the Geocode with ArcGIS processor.
As discussed, the docs for this processor does not document procedures to be performed in the ArcGIS platform, nor links to ArcGIS documentation because URLs could change, leading to broken links in our docs.
Story details: https://app.clubhouse.io/opendatasoft/story/27104
- Added the [prerequisites to use the processor](https://github.com/opendatasoft/ods-documentation/compare/develop...feature/ch27104/geocode-arcgis-processor-prereqs#diff-6fb6ea39c49323d4e1547bb6bd12a2c85c75879df454dc5f35289338f61d3f2aR8-R13) in the related docs.
- Reworded the intro to avoid two consecutive notes.
- Reworded and renamed the [procedure for configuring the Client ID and Client Secret …

Added the prerequisites to use the Geocode with ArcGIS processor

---

source/configuring_domain/03_managing_tracking/third_party_analytics.rst

This pull request updates the documentation for Matomo configuration in the back office.
On top of that, the whole "Third-party analytics" section has been reworded for better consistency, conciseness, and clarity.
Story details: https://app.clubhouse.io/opendatasoft/story/28680
- Removed the [content about support involvement](https://github.com/opendatasoft/ods-documentation/compare/feature/ch28680/matomo-configuration?expand=1#diff-c6e440d6fd65214262f0083fffdade1a620fde20b4a04f2b43186c669a247b11L63-L66)  in the configuration procedure for Matomo.
- Added a [prerequisite](https://github.com/opendatasoft/ods-documentation/compare/feature/ch28680/matomo-configuration?expand=1#diff-c6e440d6fd65214262f0083fffdade1a620fde20b4a04f2b43186c669a247b11R82-R85) so that admins now they need the …

Updated the doc for Matomo configuration in the back office

---

source/publishing_data/02_harvesting_a_catalog/harvesters/ftp_with_meta_csv.rst

This pull request adds an example of custom metadata in the doc documentation for the FTP w/ meta CSV harvester.
Story details: https://app.clubhouse.io/opendatasoft/story/28782
- Changed the variable name to use an hyphen instead of an underscore
- Added an example to help users

Added an example of custom metadata in FTP w/ meta CSV harvester docs

---

source/configuring_domain/02_managing_legal_information/legals.rst

This pull tests the [`guilabel` role ](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-guilabel)for UI terms mentioned in instructions. The purpose is to have more semantic meaning in the HTML output. When bolding terms, `<strong>` tags are generated, but UI terms are not "important". This results in having UI terms ranked higher in search results.
That's the why reason we should use the `guilabel` role instead.
Story details: https://app.clubhouse.io/opendatasoft/story/29388
- Replaced `**` with the `guilabel` role for UI terms in the Legals section of the user guide as a PoC.

Tested UI terms in guilabel roles

---

source/publishing_data/05_processing_data/processors/geojoin.rst
source/publishing_data/05_processing_data/processors/retrieve_administrative_divisions.rst
source/publishing_data/05_processing_data/processors/widgets/geodomain--de.html
source/publishing_data/05_processing_data/processors/widgets/geodomain--en.html
source/publishing_data/05_processing_data/processors/widgets/geodomain--es.html
source/publishing_data/05_processing_data/processors/widgets/geodomain--fr.html
source/publishing_data/05_processing_data/processors/widgets/geodomain--nl.html
source/publishing_data/05_processing_data/processors/widgets/geojoin--de.html
source/publishing_data/05_processing_data/processors/widgets/geojoin--en.html
source/publishing_data/05_processing_data/processors/widgets/geojoin--es.html
source/publishing_data/05_processing_data/processors/widgets/geojoin--fr.html
source/publishing_data/05_processing_data/processors/widgets/geojoin--nl.html

This pull request removed England, Scotland, and Wales from the docs for geographic processors because those countries are now included into United Kingdom. The related datasets have been already republished so that the widgets embedded within the docs display accurate and current data.
Story details: https://app.clubhouse.io/opendatasoft/story/28377
- Removed England, Scotland, and Wales from the list of countries for the Geojoin and Retrieve the administrative divisions processors.
- Fixed a [typo](https://github.com/opendatasoft/ods-documentation/compare/chore/ch28377/remove-england-scotland-wales-from-geographic?expand=1#diff-8d60fb3d2874acab4d16a491459568d762d259bf4aa8feaf8f0329de032be387R58)
- Fixed `div` width for the widgets embedded within the docs to prevent drop-down lists from …

Removed England, Scotland, and Wales from geographic processors

---

source/publishing_data/02_harvesting_a_catalog/harvesters/csw.rst

This pull request adds the new "Invert coordinates" configuration parameter to the docs for the CSW harvester and updates the docs to match the UI.
Story details: https://app.clubhouse.io/opendatasoft/story/28461
- Added the [Invert coordinates](https://github.com/opendatasoft/ods-documentation/compare/feature/ch28461/enhance-the-docs-for-the-csw-harvester?expand=1#diff-fa19c849acf40d270a0fe905120a240369a9f6e5df72ee7c840e51fe61171434R32-R33) configuration parameter with a description
- Reorder the parameters to match the UI
- Reworded a description for consistency purposes
- Removed technical name for parameters (they were mentioned between parentheses but they do not appear in the UI)
- Removed the Examples column given that only one example was provided
- Moved the example of a CSW URL …

Enhanced the docs for the CSW harvester

---

source/configuring_domain/02_managing_legal_information/legals.rst

This pull reverts #311 because using the [`guilabel` role ](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-guilabel) for UI terms mentioned in instructions does not bring major improvements but increases the complexity for translators.
That's why why using UI terms in bold characters should be preferred (`**UI term**`).
- Reverts opendatasoft/ods-documentation#311

Revert "Tested UI terms in guilabel roles"

---

source/publishing_data/04_configuring_a_source/connectors/openagenda.rst

This pull request fixes broken links in the OpenAgenda connector docs. The OpenAgenda docs have moved to https://developers.openagenda.com/
Story details: https://app.clubhouse.io/opendatasoft/story/29515
- Updated links to the OpenAgenda docs

Updated links to the OpenAgenda docs

---

source/managing_domain/03_analyzing_domain_usage/analyzing_actions_usage.rst

This pull request adds a note to the docs for the "Searches with no results" monitoring indicator so that users understand it better.
Story details: https://app.clubhouse.io/opendatasoft/story/26096
- Added a note to describe when searches can lead to no results.

As a user, I need a clear description of the "Searches with no results" indicator

---

source/publishing_data/05_processing_data/processors/normalize_date.rst

This pull request adds info about normalizing a date to the ISO 8601 date format with the Normalize Date processor.
Story details: https://app.clubhouse.io/opendatasoft/story/29548
- Added a paragraph in the intro with the syntax normalize a date to the ISO 8601 date format with the Normalize Date processor.
- Created a unique label for the "Date format pattern" section so that we can insert cross-references to this section in the docs.
- Fixed typos and grammar issues.

Make the docs for the Normalize date processor clearer

---

source/exploring_catalog_and_datasets/02_looking_up_a_dataset/visualizing_data.rst
source/exploring_catalog_and_datasets/04_getting_involved/exporting_data.rst
source/publishing_data/07_configuring_visualizations/05_configuring_calendar_view/calendar.rst

This pull request adds info about the iCalendar export.
Story details: https://app.clubhouse.io/opendatasoft/story/28030
- Added iCalendar to the [list of export formats available](https://github.com/opendatasoft/ods-documentation/compare/feature/ch28030/add-documentation-for-ical-exports?expand=1#diff-74c8168259e1d861f5b74f633846ba0ef565ae8895b4d9ce558881838e28dca4R17) in the platform
- Added some [info about the iCalendar export](https://github.com/opendatasoft/ods-documentation/compare/feature/ch28030/add-documentation-for-ical-exports?expand=1#diff-35509e152ddeff650ebbea1eb2386c3fb054e2b181cd16c510744c70634dcb20R16) in the configuration docs for the Calendar visualization

Added documentation for iCal exports

---

source/publishing_data/02_harvesting_a_catalog/harvesters/datagouv.rst

This pull request enhances the docs for the datagouv harvester.
Story details: https://app.clubhouse.io/opendatasoft/story/27660
- Added more detailed info about [finding the organization ID](https://github.com/opendatasoft/ods-documentation/compare/chore/ch27660/enhance-datagouv-harvester-docs?expand=1#diff-e513eeaf90faee60d9955eeacbfce6a39b2b72a4dd9938ed8096282d79d07760R30-R34)
- Added an exhaustive list of [filter parameters](https://github.com/opendatasoft/ods-documentation/compare/chore/ch27660/enhance-datagouv-harvester-docs?expand=1#diff-e513eeaf90faee60d9955eeacbfce6a39b2b72a4dd9938ed8096282d79d07760R36-R45) (I know that filter parameters like `format` accept some "weird" values but I don't want to provide users with an incomplete list.)
- Added more [info about values for filter …

Enhance datagouv harvester docs

---

source/publishing_data/01_creating_a_dataset/creating_a_dataset.rst
source/publishing_data/01_creating_a_dataset/dataset_limits.rst

This PR adds information about the limits that apply to Opendatasoft datasets.
Story details: https://app.shortcut.com/opendatasoft/story/27661
- Created a new subsection within "Creating a dataset"
- Added info about the max number of fields per dataset and data type
- Provided a link to contact the Support team if users exceed limits

Added info about dataset limits

---

source/publishing_data/01_creating_a_dataset/connectors/sharepoint.rst

This PR adds a note about Office admin approval in the SharePoint connectors docs.
Story details: https://app.shortcut.com/opendatasoft/story/30151
- Added a note about Office admin approval in the SharePoint connectors docs.

Added note about admin approval in SharePoint docs

---

source/_templates/header.html

The goal for this PR is to upgrade the "release note" url in the header of the helphub.
Associated Shortcut ticket:
- [sc-35817](https://app.shortcut.com/opendatasoft/story/35817/release-notes-change-url-links-for-the-release-notes).
- update the "release notes" url with https://changes.opendatasoft.com
none
none
URL for "release notes" has been changed with https://changes.opendatasoft.com
welcome

[sc-35817] Update the "release notes" url
