opendatasoft/ods-documentation

- source/_templates/footer.html
This shouldn't be merged before the corresponding PR on platform is merged.
> Slack feedback

- README.md
- source/accessibility.rst
- source/index.rst
(cherry-picked from d60fd12efbe87d24971854f44df322c96241ed89)
> Add accessibility doc page 

- source/notifications/daily_report.rst
- source/sourcing_and_processing_data/processing.rst
Maybe I should update the daily report picture... (But I let @meganelacheny decide)
> Fix [#7892] and [#7897] add doc for GeoJoin and update the daily report section

- source/editing_pages/integrate_content.rst
- source/platform_glossary.rst
- source/sourcing_and_processing_data/harvesters.rst
- source/sourcing_and_processing_data/harvesters/enigma.rst
- source/sourcing_and_processing_data/processing.rst
> Enigma harvester

- source/managing_security/saml.rst
- source/using_api/v1/query_language_and_geo_filtering.rst
> [ch7307]Added doc for the #attr function

- scripts/helpscout.py
These mods will be compliant with both Python 2 and Python 3.
Also \n\n before function definitions to be be compliant with PEP8.
> from __future__ import print_function for Python 3

- source/sourcing_and_processing_data/processors/expression.rst
Was in #98, pull request discarded because of the processors rewrite + unrelated changes.
> Change operators in expression processor (extracted from #98)

- source/sourcing_and_processing_data/processors/join_dataset.rst
this is to avoid any further misunderstanding
> Document join limitation for scheduled datasets

- source/index.rst
- source/setup.rst
~/!\ This branch must be merged after new_toc (don't forget to change the base before merging)~
> New version of "Welcome" & "Getting started" pages

- source/publishing_data/05_processing_data/processors/geojoin.rst
- source/publishing_data/05_processing_data/processors/retrieve_administrative_divisions.rst
https://app.clubhouse.io/opendatasoft/story/15927/update-georeferentials
> [ch15927] Update geodomain and geojoin referentials

- source/publishing_data/08_configuring_dataset_export/configuring_dataset_export.rst
Add documentation for:
- Additional geographical projections
- Additional export formats
- Alternative exports
> Export tab documentation

- source/configuring_domain/02_managing_legal_information/legals.rst
- source/creating_maps_charts/02_creating_advanced_charts/analyze.rst
- source/exploring_catalog_and_datasets/04_getting_involved/exporting_data.rst
- source/publishing_data/01_creating_a_dataset/creating_dataset_with_images.rst
- source/publishing_data/05_processing_data/processors/geo_distance.rst
- source/publishing_data/05_processing_data/processors/join_dataset.rst
- Processors documentation:
- Join dataset: document "Republish all records upon update" option
- Geo distance: fix error (output is in kilometers, not in meters)
- Exporting data documentation: add note about Shapefile exports limitations
- Creating a dataset with media files documentation: improve documentation to highlight which formats generate a thumbnail, and which formats do not (e.g PDF)
- Chart Builder, Cookies & Trackers documentations: fix typos
> Quick wins (August 2019)

- source/publishing_data/01_creating_a_dataset/sourcing_data.rst
Reverts opendatasoft/ods-documentation#201
> Revert "Note about HTTP headers"

- source/publishing_data/05_processing_data/processors/retrieve_administrative_divisions.rst
- source/publishing_data/05_processing_data/processors/widgets/geodomain--de.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--en.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--es.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--fr.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--nl.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--de.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--en.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--es.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--fr.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--nl.html
Change facets default sort for ods-geodomain widget:
- Select a country (alphanum)
- Select an administrative level (num)
Change facets default sort for ods-geojoin widget:
- Select a country (alphanum)
- Select an administrative level (num)
- Select a year (-num)
> Sort facets of geodomain/geojoin widget and get back retrieve_admin processor description

- source/publishing_data/01_creating_a_dataset/sourcing_data.rst
Reverts opendatasoft/ods-documentation#206
> Revert "Revert "Note about HTTP headers""

- source/_locale/de/LC_MESSAGES/configuring_domain/03_managing_tracking/third_party_analytics.po
- source/_locale/es/LC_MESSAGES/configuring_domain/03_managing_tracking/third_party_analytics.po
- source/_locale/fr/LC_MESSAGES/configuring_domain/03_managing_tracking/third_party_analytics.po
- source/_locale/nl/LC_MESSAGES/configuring_domain/03_managing_tracking/third_party_analytics.po
> Mep 05/12/2019

- source/publishing_data/01_creating_a_dataset/federating_data.rst
- source/publishing_data/05_processing_data/processors/expression.rst
- Addition of `week` function in Expression processor
- Update of _Federating data_ documentation: automatic update of federated datasets metadata
> Quick wins (January 2020)

- source/exploring_catalog_and_datasets/01_navigating_the_catalog/catalog.rst
- source/publishing_data/06_configuring_metadata/interoperability_metadata.rst
Related to: https://github.com/opendatasoft/ods-documentation-explore-api/pull/57
> DCAT-AP documentation

- source/publishing_data/01_creating_a_dataset/sourcing_data.rst
- source/publishing_data/04_configuring_a_source/configuring_source.rst
- source/publishing_data/04_configuring_a_source/connectors/census.rst
I extract my examples from the census API guide: [https://www.census.gov/data/developers/guidance/api-user-guide.Overview.html](https://www.census.gov/data/developers/guidance/api-user-guide.Overview.html)
I tried to present two examples to cover the features as much as possible. If it is still unclear or on contrary too much, do not hesitate to tell me.
Thanks for your reviews
> census extractor documentation

- source/_templates/header.html
Link to codelibrary. No translation needed, it's only EN.
> Change discovery link to code library

- source/publishing_data/05_processing_data/processors/widgets/geodomain--de.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--en.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--es.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--fr.html
- source/publishing_data/05_processing_data/processors/widgets/geodomain--nl.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--de.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--en.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--es.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--fr.html
- source/publishing_data/05_processing_data/processors/widgets/geojoin--nl.html
Upgrading the widgets scripts used in the geojoin and retrieve administrative divisions embeds.
> Upgrade widgets script to the latest-v2 target

- source/publishing_data/04_configuring_a_source/configuring_source.rst
- source/publishing_data/04_configuring_a_source/connectors/openagenda.rst
Story details: [#25093](https://app.clubhouse.io/opendatasoft/story/25093)
> [ch25093] Documentation for the OpenAgenda extractor

- source/configuring_domain/02_managing_legal_information/legals.rst
Story details: https://app.clubhouse.io/opendatasoft/story/25458
Changelog:
- Added info about the licenses available by default
- Restructured the licenses section to have two separate subsections for the configuration procedure and the reference information about the licenses
- Reworded the information within the whole Licenses section
> Explain the default licences

- source/configuring_domain/02_managing_legal_information/legals.rst
- source/creating_content/01_creating_content_page/integrate_content.rst
- source/creating_content/tutorials/advanced_dashboard/advanced_dashboard.rst
- source/customizing_look_and_feel/04_configuring_data_visualizations/data_visualizations.rst
- source/customizing_look_and_feel/06_customizing_theme/theme.rst
- source/exploring_catalog_and_datasets/04_getting_involved/sharing_embedding_data_visualizations.rst
- source/exploring_catalog_and_datasets/04_getting_involved/using_api.rst
- source/managing_domain/01_managing_users_and_groups/users.rst
- source/publishing_data/01_creating_a_dataset/creating_dataset_with_images.rst
- source/publishing_data/01_creating_a_dataset/sourcing_data.rst
- source/publishing_data/02_harvesting_a_catalog/harvesters/ckan.rst
- source/publishing_data/02_harvesting_a_catalog/harvesters/csw.rst
- source/publishing_data/02_harvesting_a_catalog/harvesters/dbnomics.rst
- source/publishing_data/02_harvesting_a_catalog/harvesters/enigma.rst
- source/publishing_data/02_harvesting_a_catalog/harvesters/junar.rst
- source/publishing_data/02_harvesting_a_catalog/harvesters/quandl.rst
- source/publishing_data/04_configuring_a_source/connectors/airtable.rst
- source/publishing_data/04_configuring_a_source/connectors/geojson.rst
- source/publishing_data/04_configuring_a_source/connectors/salesforce.rst
- source/publishing_data/04_configuring_a_source/connectors/wfs.rst
- source/publishing_data/05_processing_data/defining_a_dataset_schema.rst
- source/publishing_data/05_processing_data/processors/create_geopoint.rst
- source/publishing_data/05_processing_data/processors/extract_text.rst
- source/publishing_data/05_processing_data/processors/ip_address_to_geo_coordinates.rst
- source/publishing_data/05_processing_data/processors/nominatim_geocoder.rst
- source/publishing_data/05_processing_data/processors/normalize_projection_reference.rst
- source/publishing_data/05_processing_data/processors/normalize_url.rst
- source/publishing_data/05_processing_data/processors/replace_via_regexp.rst
- source/setup.rst
This PR aims to fix broken links and redirects reported by running `make linkcheck`.
Associated Clubhouse story: [#26028](https://app.clubhouse.io/opendatasoft/story/26028/fix-broken-hyperlinks-in-the-docs )
Fixed broken links and grammar issues.
> Fixed broken links and redirects

- source/publishing_data/01_creating_a_dataset/sourcing_data.rst
This pull request removes the note "Opendatasoft can also develop and integrate customer-specific Web APIs. Opendatasoft connectivity toolkit makes it possible to develop performant and secured connectors supporting incremental data processing" from the "Sourcing data" section of the User Guide.
Story details: https://app.clubhouse.io/opendatasoft/story/27221
- Removed the related note from the "Sourcing data" section of the User Guide
> Removed the note about "customer-specific Web API integration" from the user guide

- source/publishing_data/05_processing_data/adding_processors_to_a_dataset.rst
- source/publishing_data/05_processing_data/processors/correct_geo_shape.rst
This pull request adds the documentation for the **Correct geo shape** connector.
Story details: https://app.clubhouse.io/opendatasoft/story/25457
- Added the [docs for the processor](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25457/document-correct-shape-processor?expand=1#diff-2d587846c781cc41dc3fd7fa2a12d861e2f45ab934328c0369c28b0cc2500f91).
- Added the connector to the [overview of the geographical processor](https://github.com/opendatasoft/ods-documentation/compare/feature/ch25457/document-correct-shape-processor?expand=1#diff-05ef0d2a65dc5e632f208b8577b09fbe0fac3253db3a2d03b6c55b01cad562bd).
> Added docs for the correct_shape processor

- source/publishing_data/04_configuring_a_source/connectors/spreadsheet.rst
This pull request adds good spreadsheet practices to the spreadsheet connector docs. The CS team regularly encounters issues related to spreadsheets with locked rows, blank cells, etc.
The purpose is to help users prepare their files for easier uploading of files.
The content has already been reviewed by @SylvainO and validated with him.
Story details: https://app.clubhouse.io/opendatasoft/story/26651
- Added a [section for good practices](https://github.com/opendatasoft/ods-documentation/compare/feature/ch26651/spreadsheet-processor-best-practices?expand=1#diff-ea434514e50b17f80f356663bcd4edd86eb2373d211e8c83ef75621ab8c7fb60R16-R27) in the spreadsheet connector docs.
- Fixed grammar issues and inconsistencies.
> Added good spreadsheet practices to spreadsheet connector docs

- source/publishing_data/04_configuring_a_source/connectors/spreadsheet.rst
Reverts opendatasoft/ods-documentation#285
> Revert "Added good spreadsheet practices to spreadsheet connector docs"

- source/publishing_data/04_configuring_a_source/connectors/spreadsheet.rst
This pull request applies the changes introduced in #285 again, due to an "emergency revert".
Story details: https://app.clubhouse.io/opendatasoft/story/26651
- Added a [section for good practices](https://github.com/opendatasoft/ods-documentation/compare/feature/ch26651/spreadsheet-processor-best-practices?expand=1#diff-ea434514e50b17f80f356663bcd4edd86eb2373d211e8c83ef75621ab8c7fb60R16-R27) in the spreadsheet connector docs.
- Fixed grammar issues and inconsistencies.
> Added good spreadsheet practices to spreadsheet connector docs again

- source/_templates/layout.html
This pull request adds Matomo's tracking code to user guide pages.
Story details: https://app.clubhouse.io/opendatasoft/story/28195
- Added Matomo tracking code to HTML template.
> Added Matomo tracking code to HTML template

- source/conf.py
This pull request updates the Sphinx configuration to get content from list items indexed by Algolia's Docsearch and make it available in search results.
Story details: https://app.clubhouse.io/opendatasoft/story/29335
- Set `html_compact_lists` to `False` in conf.py: https://github.com/opendatasoft/ods-documentation/blob/85f39f9f50fbd2ee64f5ad6e5cc9a4c1a259b8b8/source/conf.py#L322
> Updated Sphinx configuration

- source/publishing_data/07_configuring_visualizations/06_configuring_custom_view/custom.rst
- source/publishing_data/07_configuring_visualizations/index.rst
This pull request removes remaining occurrences of OpenDataSoft from the docs.
Story details: https://app.clubhouse.io/opendatasoft/story/29331
- Removed remaining occurrences of OpenDataSoft
> Removed remaining occurrences of OpenDataSoft

- source/managing_domain/01_managing_users_and_groups/access_requests.rst
- source/managing_domain/01_managing_users_and_groups/groups.rst
- source/managing_domain/01_managing_users_and_groups/users.rst
This pull request adds a procedure so that portal admins know how to invite users to a domain.
Story details: https://app.clubhouse.io/opendatasoft/story/27532
- Added the related [procedure](https://github.com/opendatasoft/ods-documentation/compare/develop...feature/ch27532/inviting-users-on-domain#diff-c315de1b2dbb65aeac3e036ac60deae48aba1b666e6ac2810487dd2a594f3f6aR9-R26)
- Fixed typos, styling and line break issues
> Inviting users to a domain

- source/index.rst
This pull request replaces occurrences of "manual" with "guide" on the user guide's home page.
Story details: https://app.shortcut.com/opendatasoft/story/29931
- Replaced "manual" with "guide".
> Fixed inconsistencies between "guide" and "manual"

- source/publishing_data/01_creating_a_dataset/configuring_remote_service.rst
Story details: https://app.shortcut.com/opendatasoft/story/32658
> Airtable is not available by default anymore

- .travis.yml
Attempt to limit the deprecated documentation to ES, DE and NL and remove FR and EN from the prod
> Remove builds for EN and FR
